import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider"
import { Toaster } from 'react-hot-toast'
import "./globals.css";
import Header from "@/components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link
          rel="stylesheet"
          href="https://unpkg.com/react-quill@1.3.3/dist/quill.snow.css"
        />
      </head>
      <body
        className="font-mono"
      >
        <Header />
        <main className="bg-gray-100 min-h-screen text-black tracking-tighter">
          {children}
        </main>
        <Toaster />
      </body>
    </html>
  );
}
